# Use an official Node.js runtime as the base image
FROM node:14

# Set the working directory inside the container
WORKDIR /src

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install project dependencies
RUN npm install

# Copy the rest of your application code to the container
COPY . .

RUN npm run build

# Expose the port that your Nest.js application will run on (default is 8080)
EXPOSE 8080

# Start the server using the production build
CMD [ "node", "dist/main.js" ]
