version: '2.18.1'
services:
  mysql:
    image: mysql:latest
    ports:
      - '3307:3306'
    restart: always
    mem_limit: 512m
    mem_reservation: 128M
    cpus: 0.5
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: quizapp
      MYSQL_USER: longq
      MYSQL_PASSWORD: 123456
    volumes:
      - ./data/mysql:/var/lib/mysql
