version: '2.18.1'
services:
  backend:
    build: ./
    container_name: nestjs_api
    environment:
      - DATABASE_HOST=13.54.6.157
      - DATABASE_PORT=3306
      - DATABASE_USERNAME=longq
      - DATABASE_PASSWORD=longq@123456
      - DATABASE_NAME=quizapp
    ports:
      - '8080:80'
