# Use the official Node.js image as the base image
FROM node:14

# Set the working directory inside the container
WORKDIR /src

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port your NestJS app is running on
EXPOSE 8080

# Start the NestJS app
CMD ["npm", "run", "dev"]
